/*FILTROS DE GRUPO*/

SELECT NOME,DEPARTAMENTO,SALARIO
FROM FUNCIONARIOS 
WHERE SALARIO > 10000;

/*FILTRO BASEADO EM STRINGS*/

SELECT NOME,DEPARTAMENTO,SALARIO
FROM FUNCIONARIOS 
WHERE DEPARTAMENTO = 'Ferramentas';

/*FILTRO BASEADO EM MÚLTIPLOS TIPOS E COLUNAS - CONSIDERAR OR E AND*/
SELECT NOME,DEPARTAMENTO,SALARIO
FROM FUNCIONARIOS 
WHERE DEPARTAMENTO = 'Ferramentas'
AND
SALARIO > 100000;

/*(em relacionamentos (1,1), o filtro 'and' utilizado na mesma coluna sempre dará falso). POR EXEMPLO:*/
SELECT NOME,DEPARTAMENTO,SALARIO
FROM FUNCIONARIOS 
WHERE DEPARTAMENTO = 'Ferramentas'
AND
DEPARTAMENTO = 'Books';


/*FILTROS BASEADOS EM PADRÃO DE CARACTERES (% = QUALQUER COISA)*/
SELECT DEPARTAMENTO, SUM(SALARIO) AS "TOTAL"
FROM FUNCIONARIOS
WHERE DEPARTAMENTO LIKE 'Be%'
GROUP BY DEPARTAMENTO;

SELECT DEPARTAMENTO, SUM(SALARIO) AS "TOTAL"
FROM FUNCIONARIOS
WHERE DEPARTAMENTO LIKE 'B%s'
GROUP BY DEPARTAMENTO;

/*FILTRANDO O AGRUPAMENTO DE SALARIOS QUE SÃO MAIORES QUE 40.000*/

SELECT DEPARTAMENTO, SUM(SALARIO) AS "TOTAL"
FROM FUNCIONARIOS
WHERE DEPARTAMENTO LIKE 'B%'
GROUP BY DEPARTAMENTO
HAVING SUM(SALARIO) > 40000;


------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*FILTROS DE CONTADORES*/

SELECT COUNT(*) FROM FUNCIONARIOS;

/*FILTRANDO NÚMERO DE FUNCIONÁRIOS E OS DO SEXO MASCULINO.

FORMA PIOR E LONGA:*/
SELECT COUNT(*) AS "QUANTIDADE TOTAL", (SELECT COUNT(*)
FROM FUNCIONARIOS
WHERE SEXO = 'Masculino'
GROUP BY SEXO) AS "Masculino"
FROM FUNCIONARIOS;

/*FORMA MAIS FACIL E MELHOR: ISSO SERVE PRA FILTRAR QUALQUER COISA!!!*/

SELECT COUNT(*) AS "QUANTIDADE TOTAL",
COUNT(*) FILTER(WHERE SEXO = 'Masculino') AS "MASCULINO",
COUNT(*) FILTER(WHERE DEPARTAMENTO = 'Books') AS "BOOKS",
COUNT(*) FILTER(WHERE SALARIO > 90000) AS "SALARIO > 90K"
FROM FUNCIONARIOS;
