/* EXERCICIOS DML */

INSERT INTO CLIENTE VALUES(NULL,'FLAVIO','M','FLAVIO@IG.COM','4657765');
INSERT INTO CLIENTE VALUES(NULL,'ANDRE','M','ANDRE@GLOBO.COM','7687567');
INSERT INTO CLIENTE VALUES(NULL,'GIOVANA','F',NULL,'0876655');
INSERT INTO CLIENTE VALUES(NULL,'KARLA','M','KARLA@GMAIL.COM','545676778');
INSERT INTO CLIENTE VALUES(NULL,'DANIELE','M','DANIELE@GMAIL.COM','43536789');
INSERT INTO CLIENTE VALUES(NULL,'LORENA','M',NULL,'774557887');
INSERT INTO CLIENTE VALUES(NULL,'EDUARDO','M',NULL,'54376457');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','12436767');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','3423565');
INSERT INTO CLIENTE VALUES(NULL,'ELAINE','M','ELAINE@GLOBO.COM','32567763');
INSERT INTO CLIENTE VALUES(NULL,'CARMEM','M','CARMEM@IG.COM','787832213');
INSERT INTO CLIENTE VALUES(NULL,'ADRIANA','F','ADRIANA@GMAIL.COM','88556942');
INSERT INTO CLIENTE VALUES(NULL,'JOICE','F','JOICE@GMAIL.COM','55412256');

/* CADASTRE UM ENDEREÇO PARA CADA CLIENTE */

INSERT INTO ENDEREÇO VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',9);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',10);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',11);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',12);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',13);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',14);
INSERT INTO ENDEREÇO VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',15);
INSERT INTO ENDEREÇO VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',16);
INSERT INTO ENDEREÇO VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',17);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',18);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',19);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',20);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',8);

/* CADASTRE TELEFONES PARA OS CLIENTES */

INSERT INTO TELEFONE VALUES(NULL,'RES','68976565',9);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99656675',9);
INSERT INTO TELEFONE VALUES(NULL,'CEL','33567765',11);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88668786',11);
INSERT INTO TELEFONE VALUES(NULL,'COM','55689654',11);
INSERT INTO TELEFONE VALUES(NULL,'COM','88687979',12);
INSERT INTO TELEFONE VALUES(NULL,'COM','88965676',13);
INSERT INTO TELEFONE VALUES(NULL,'CEL','89966809',15);
INSERT INTO TELEFONE VALUES(NULL,'COM','88679978',16);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99655768',17);
INSERT INTO TELEFONE VALUES(NULL,'RES','89955665',18);
INSERT INTO TELEFONE VALUES(NULL,'RES','77455786',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','89766554',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','77755785',20);
INSERT INTO TELEFONE VALUES(NULL,'COM','44522578',20);


/*CORRIGINDO DADOS UTILIZANDO 'IN' = CONJUNTO DE LINHAS DIFERENTES*/

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE IN (11, 12, 13, 17, 18);

UPDATE CLIENTE
SET SEXO = 'M'
WHERE IDCLIENTE = 15;


/* RELATORIO GERAL DE TODOS OS CLIENTES */

SELECT C.IDCLIENTE,C.NOME,C.SEXO,C.EMAIL,C.CPF,E.RUA,E.BAIRRO,E.CIDADE,E.ESTADO,T.TIPO,T.NUMERO
FROM CLIENTE C
INNER JOIN ENDEREÇO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

+-----------+---------+------+-------------------+-------------+-----------------------+------------+----------------+--------+------+-------------+
| IDCLIENTE | NOME    | SEXO | EMAIL             | CPF         | RUA                   | BAIRRO     | CIDADE         | ESTADO | TIPO | NUMERO      |
+-----------+---------+------+-------------------+-------------+-----------------------+------------+----------------+--------+------+-------------+
|         5 | JORGE   | M    | JORGE@YAHOO.COM   | 89545581487 | RUA URUGUAIANA        | CENTRO     | VITÓRIA        | ES     | CEL  | 84645875251 |
|         5 | JORGE   | M    | JORGE@YAHOO.COM   | 89545581487 | RUA URUGUAIANA        | CENTRO     | VITÓRIA        | ES     | RES  | 81568499251 |
|         1 | JOAO    | M    | JOAO@IG.COM       | 76567587887 | RUA CAPITAO HERNES    | CENTRO     | RIO DE JANEIRO | RJ     | CEL  | 84614547854 |
|         1 | JOAO    | M    | JOAO@IG.COM       | 76567587887 | RUA CAPITAO HERNES    | CENTRO     | RIO DE JANEIRO | RJ     | COM  | 84654998575 |
|         1 | JOAO    | M    | JOAO@IG.COM       | 76567587887 | RUA CAPITAO HERNES    | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 84646516214 |
|         2 | CARLOS  | M    | CARLOS@IG.COM     | 76567587486 | RUA ALFANDEGA         | ESTÁCIO    | RIO DE JANEIRO | RJ     | CEL  | 84651235975 |
|         3 | ANA     | F    | ANA@GMAIL.COM     | 76999587251 | RUA PRESIDENTE VARGAS | JARDINS    | SAO PAULO      | SP     | CEL  | 84147885695 |
|         5 | JORGE   | M    | JORGE@YAHOO.COM   | 89545581487 | RUA URUGUAIANA        | CENTRO     | VITÓRIA        | ES     | COM  | 97645125485 |
|         5 | JORGE   | M    | JORGE@YAHOO.COM   | 89545581487 | RUA URUGUAIANA        | CENTRO     | VITÓRIA        | ES     | RES  | 84645456512 |
|         2 | CARLOS  | M    | CARLOS@IG.COM     | 76567587486 | RUA ALFANDEGA         | ESTÁCIO    | RIO DE JANEIRO | RJ     | CEL  | 15615648956 |
|         9 | ANDRE   | M    | ANDRE@GLOBO.COM   | 7687567     | RUA GUEDES            | CASCADURA  | B. HORIZONTE   | MG     | RES  | 68976565    |
|         9 | ANDRE   | M    | ANDRE@GLOBO.COM   | 7687567     | RUA GUEDES            | CASCADURA  | B. HORIZONTE   | MG     | CEL  | 99656675    |
|        11 | KARLA   | F    | KARLA@GMAIL.COM   | 545676778   | RUA VISCONDESSA       | CENTRO     | RIO DE JANEIRO | RJ     | CEL  | 33567765    |
|        11 | KARLA   | F    | KARLA@GMAIL.COM   | 545676778   | RUA VISCONDESSA       | CENTRO     | RIO DE JANEIRO | RJ     | CEL  | 88668786    |
|        11 | KARLA   | F    | KARLA@GMAIL.COM   | 545676778   | RUA VISCONDESSA       | CENTRO     | RIO DE JANEIRO | RJ     | COM  | 55689654    |
|        12 | DANIELE | F    | DANIELE@GMAIL.COM | 43536789    | RUA NELSON MANDELA    | COPACABANA | RIO DE JANEIRO | RJ     | COM  | 88687979    |
|        13 | LORENA  | F    | NULL              | 774557887   | RUA ARAUJO LIMA       | CENTRO     | VITORIA        | ES     | COM  | 88965676    |
|        15 | ANTONIO | M    | ANTONIO@IG.COM    | 12436767    | AV CAPITAO ANTUNES    | CENTRO     | CURITIBA       | PR     | CEL  | 89966809    |
|        16 | ANTONIO | M    | ANTONIO@UOL.COM   | 3423565     | AV CARLOS BARROSO     | JARDINS    | SAO PAULO      | SP     | COM  | 88679978    |
|        17 | ELAINE  | F    | ELAINE@GLOBO.COM  | 32567763    | ALAMEDA SAMPAIO       | BOM RETIRO | CURITIBA       | PR     | CEL  | 99655768    |
|        18 | CARMEM  | F    | CARMEM@IG.COM     | 787832213   | RUA DA LAPA           | LAPA       | SAO PAULO      | SP     | RES  | 89955665    |
|        19 | ADRIANA | F    | ADRIANA@GMAIL.COM | 88556942    | RUA GERONIMO          | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 77455786    |
|        19 | ADRIANA | F    | ADRIANA@GMAIL.COM | 88556942    | RUA GERONIMO          | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 89766554    |
|        20 | JOICE   | F    | JOICE@GMAIL.COM   | 55412256    | RUA GOMES FREIRE      | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 77755785    |
|        20 | JOICE   | F    | JOICE@GMAIL.COM   | 55412256    | RUA GOMES FREIRE      | CENTRO     | RIO DE JANEIRO | RJ     | COM  | 44522578    |
+-----------+---------+------+-------------------+-------------+-----------------------+------------+----------------+--------+------+-------------+

/* RELATORIO DE HOMENS */

SELECT C.IDCLIENTE,C.NOME,C.SEXO,C.EMAIL,C.CPF,E.RUA,E.BAIRRO,E.CIDADE,E.ESTADO,T.TIPO,T.NUMERO
FROM CLIENTE C
INNER JOIN ENDEREÇO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'M';

+-----------+---------+------+-----------------+-------------+--------------------+-----------+----------------+--------+------+-------------+
| IDCLIENTE | NOME    | SEXO | EMAIL           | CPF         | RUA                | BAIRRO    | CIDADE         | ESTADO | TIPO | NUMERO      |
+-----------+---------+------+-----------------+-------------+--------------------+-----------+----------------+--------+------+-------------+
|         1 | JOAO    | M    | JOAO@IG.COM     | 76567587887 | RUA CAPITAO HERNES | CENTRO    | RIO DE JANEIRO | RJ     | CEL  | 84614547854 |
|         1 | JOAO    | M    | JOAO@IG.COM     | 76567587887 | RUA CAPITAO HERNES | CENTRO    | RIO DE JANEIRO | RJ     | COM  | 84654998575 |
|         1 | JOAO    | M    | JOAO@IG.COM     | 76567587887 | RUA CAPITAO HERNES | CENTRO    | RIO DE JANEIRO | RJ     | RES  | 84646516214 |
|         2 | CARLOS  | M    | CARLOS@IG.COM   | 76567587486 | RUA ALFANDEGA      | ESTÁCIO   | RIO DE JANEIRO | RJ     | CEL  | 84651235975 |
|         2 | CARLOS  | M    | CARLOS@IG.COM   | 76567587486 | RUA ALFANDEGA      | ESTÁCIO   | RIO DE JANEIRO | RJ     | CEL  | 15615648956 |
|         5 | JORGE   | M    | JORGE@YAHOO.COM | 89545581487 | RUA URUGUAIANA     | CENTRO    | VITÓRIA        | ES     | CEL  | 84645875251 |
|         5 | JORGE   | M    | JORGE@YAHOO.COM | 89545581487 | RUA URUGUAIANA     | CENTRO    | VITÓRIA        | ES     | RES  | 81568499251 |
|         5 | JORGE   | M    | JORGE@YAHOO.COM | 89545581487 | RUA URUGUAIANA     | CENTRO    | VITÓRIA        | ES     | COM  | 97645125485 |
|         5 | JORGE   | M    | JORGE@YAHOO.COM | 89545581487 | RUA URUGUAIANA     | CENTRO    | VITÓRIA        | ES     | RES  | 84645456512 |
|         9 | ANDRE   | M    | ANDRE@GLOBO.COM | 7687567     | RUA GUEDES         | CASCADURA | B. HORIZONTE   | MG     | RES  | 68976565    |
|         9 | ANDRE   | M    | ANDRE@GLOBO.COM | 7687567     | RUA GUEDES         | CASCADURA | B. HORIZONTE   | MG     | CEL  | 99656675    |
|        15 | ANTONIO | M    | ANTONIO@IG.COM  | 12436767    | AV CAPITAO ANTUNES | CENTRO    | CURITIBA       | PR     | CEL  | 89966809    |
|        16 | ANTONIO | M    | ANTONIO@UOL.COM | 3423565     | AV CARLOS BARROSO  | JARDINS   | SAO PAULO      | SP     | COM  | 88679978    |
+-----------+---------+------+-----------------+-------------+--------------------+-----------+----------------+--------+------+-------------+

/* RELATORIO DE MULHERES */

SELECT C.IDCLIENTE,C.NOME,C.SEXO,C.EMAIL,C.CPF,E.RUA,E.BAIRRO,E.CIDADE,E.ESTADO,T.TIPO,T.NUMERO
FROM CLIENTE C
INNER JOIN ENDEREÇO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F';

+-----------+---------+------+-------------------+-------------+-----------------------+------------+----------------+--------+------+-------------+
| IDCLIENTE | NOME    | SEXO | EMAIL             | CPF         | RUA                   | BAIRRO     | CIDADE         | ESTADO | TIPO | NUMERO      |
+-----------+---------+------+-------------------+-------------+-----------------------+------------+----------------+--------+------+-------------+
|         3 | ANA     | F    | ANA@GMAIL.COM     | 76999587251 | RUA PRESIDENTE VARGAS | JARDINS    | SAO PAULO      | SP     | CEL  | 84147885695 |
|        11 | KARLA   | F    | KARLA@GMAIL.COM   | 545676778   | RUA VISCONDESSA       | CENTRO     | RIO DE JANEIRO | RJ     | CEL  | 33567765    |
|        11 | KARLA   | F    | KARLA@GMAIL.COM   | 545676778   | RUA VISCONDESSA       | CENTRO     | RIO DE JANEIRO | RJ     | CEL  | 88668786    |
|        11 | KARLA   | F    | KARLA@GMAIL.COM   | 545676778   | RUA VISCONDESSA       | CENTRO     | RIO DE JANEIRO | RJ     | COM  | 55689654    |
|        12 | DANIELE | F    | DANIELE@GMAIL.COM | 43536789    | RUA NELSON MANDELA    | COPACABANA | RIO DE JANEIRO | RJ     | COM  | 88687979    |
|        13 | LORENA  | F    | NULL              | 774557887   | RUA ARAUJO LIMA       | CENTRO     | VITORIA        | ES     | COM  | 88965676    |
|        17 | ELAINE  | F    | ELAINE@GLOBO.COM  | 32567763    | ALAMEDA SAMPAIO       | BOM RETIRO | CURITIBA       | PR     | CEL  | 99655768    |
|        18 | CARMEM  | F    | CARMEM@IG.COM     | 787832213   | RUA DA LAPA           | LAPA       | SAO PAULO      | SP     | RES  | 89955665    |
|        19 | ADRIANA | F    | ADRIANA@GMAIL.COM | 88556942    | RUA GERONIMO          | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 77455786    |
|        19 | ADRIANA | F    | ADRIANA@GMAIL.COM | 88556942    | RUA GERONIMO          | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 89766554    |
|        20 | JOICE   | F    | JOICE@GMAIL.COM   | 55412256    | RUA GOMES FREIRE      | CENTRO     | RIO DE JANEIRO | RJ     | RES  | 77755785    |
|        20 | JOICE   | F    | JOICE@GMAIL.COM   | 55412256    | RUA GOMES FREIRE      | CENTRO     | RIO DE JANEIRO | RJ     | COM  | 44522578    |
+-----------+---------+------+-------------------+-------------+-----------------------+------------+----------------+--------+------+-------------+


/* QUANTIDADE DE HOMENS E MULHERES */

SELECT SEXO, COUNT(*) AS 'QUANTIDADE' FROM CLIENTE
GROUP BY SEXO;

+------+------------+
| SEXO | QUANTIDADE |
+------+------------+
| M    |         12 |
| F    |          8 |
+------+------------+

/* IDS E EMAIL DAS MULHERES QUE MOREM NO CENTRO DO RIO DE JANEIRO E NÃO TENHAM CELULAR */

SELECT C.IDCLIENTE,C.EMAIL,C.NOME,C.SEXO,E.BAIRRO,T.TIPO FROM CLIENTE C
INNER JOIN ENDEREÇO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE C.SEXO = 'F'
AND BAIRRO = 'CENTRO'
AND CIDADE = 'RIO DE JANEIRO'
AND TIPO IN('RES','COM');

/* PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA O PROGRAMADOR */

SELECT C.IDCLIENTE,C.NOME,C.EMAIL,E.ESTADO,T.NUMERO AS 'CELULAR' FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDEREÇO E
ON C.IDCLIENTE = E.ID_CLIENTE
WHERE TIPO = 'CEL'
AND ESTADO = 'RJ';

+-----------+--------+-----------------+--------+-------------+
| IDCLIENTE | NOME   | EMAIL           | ESTADO | CELULAR     |
+-----------+--------+-----------------+--------+-------------+
|         1 | JOAO   | JOAO@IG.COM     | RJ     | 84614547854 |
|         2 | CARLOS | CARLOS@IG.COM   | RJ     | 84651235975 |
|         2 | CARLOS | CARLOS@IG.COM   | RJ     | 15615648956 |
|        11 | KARLA  | KARLA@GMAIL.COM | RJ     | 33567765    |
|        11 | KARLA  | KARLA@GMAIL.COM | RJ     | 88668786    |
+-----------+--------+-----------------+--------+-------------+

/* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR  DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA O PROGRAMADOR */

SELECT C.IDCLIENTE,C.NOME,C.EMAIL,T.NUMERO AS 'CELULAR' FROM CLIENTE C
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDEREÇO E 
ON C.IDCLIENTE = E.ID_CLIENTE
WHERE SEXO = 'F'
AND ESTADO = 'SP';

+-----------+--------+---------------+-------------+
| IDCLIENTE | NOME   | EMAIL         | CELULAR     |
+-----------+--------+---------------+-------------+
|         3 | ANA    | ANA@GMAIL.COM | 84147885695 |
|        18 | CARMEM | CARMEM@IG.COM | 89955665    |
+-----------+--------+---------------+-------------+