/*Construa um banco de dados para o estoque de uma livraria*/

/*REQUISITOS*/

NOME DO LIVRO - CARACTERES(30)
NOME DO AUTOR - CARACTERES(30)
SEXO DO AUTOR - CARACTERES(1)
NÚMERO DE PÁGINAS - NUMÉRICO (11)
NOME DA EDITORA - CARACTERES(30)
VALOR DO LIVRO - NUMÉRICO (11)
ESTADO (UF) DA EDITORA - CARACTERES(2)
ANO DA PUBLICAÇÃO - NUMÉRICO (4)

/* COMECANDO */
CREATE DATABASE LIVRARIA;

USE LIVRARIA;

CREATE TABLE LIVROS(
	NOME_DO_LIVRO VARCHAR(30),
	NOME_DO_AUTOR VARCHAR(30),
	SEXO_DO_AUTOR CHAR(1),
	NÚMERO_DE_PÁGINAS INT(11),
	NOME_DA_EDITORA VARCHAR(30),
	VALOR_DO_LIVRO VARCHAR(11), /* DEVERIA TER USADO FLOAT */
	ESTADO_UF_DA_EDITORA CHAR(2),
	ANO_PUBLICADO INT(4)
);

/*ENTRADA DE DADOS FICTÍCIOS*/
INSERT INTO LIVROS (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NÚMERO_DE_PÁGINAS,
NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_UF_DA_EDITORA,ANO_PUBLICADO)
VALUES ('Cavaleiro_Real','Ana Claudia','F',465,'Atlas','46,9','RJ',2009);
INSERT INTO LIVROS (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NÚMERO_DE_PÁGINAS,
NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_UF_DA_EDITORA,ANO_PUBLICADO)
VALUES ('SQL para leigos','João Nunes','M',450,'Addison','98','SP',2018);
INSERT INTO LIVROS (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NÚMERO_DE_PÁGINAS,
NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_UF_DA_EDITORA,ANO_PUBLICADO)
VALUES ('Receitas Caseiras','Celia Tavares','F',210,'Atlas','45','RJ',2008);
INSERT INTO LIVROS (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NÚMERO_DE_PÁGINAS,
NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_UF_DA_EDITORA,ANO_PUBLICADO)
VALUES ('Pessoas Efetivas','Eduardo Santos','M',390,'Beta','78.99','RJ',2018);
INSERT INTO LIVROS (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NÚMERO_DE_PÁGINAS,
NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_UF_DA_EDITORA,ANO_PUBLICADO)
VALUES ('Hábitos Saudáveis','Eduardo Santos','M',630,'Beta','150.98','RJ',2019);
INSERT INTO LIVROS (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NÚMERO_DE_PÁGINAS,
NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_UF_DA_EDITORA,ANO_PUBLICADO)
VALUES ('A Casa Marrom','Hermes Macedo','M',250,'Bubba','60','MG',2016);
INSERT INTO LIVROS (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NÚMERO_DE_PÁGINAS,
NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_UF_DA_EDITORA,ANO_PUBLICADO)
VALUES ('Estacio Querido','Geraldo Francisco','M',310,'Insignia','100','ES',2015);
INSERT INTO LIVROS (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NÚMERO_DE_PÁGINAS,
NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_UF_DA_EDITORA,ANO_PUBLICADO)
VALUES ('Pra sempre amigas','Leda Silva','F',510,'Insignia','78.98','ES',2011);
INSERT INTO LIVROS (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NÚMERO_DE_PÁGINAS,
NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_UF_DA_EDITORA,ANO_PUBLICADO)
VALUES ('Copas Inesqueciveis','Marco Alcantara','M',200,'Larson','130.98','RS',2018);
INSERT INTO LIVROS (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NÚMERO_DE_PÁGINAS,
NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_UF_DA_EDITORA,ANO_PUBLICADO)
VALUES ('O poder da mente','Clara Mafra','F',120,'Continental','56.58','SP',2017);


/*CONSULTANDO DADOS:*/
SELECT * FROM LIVROS; /*ASTERISCO APENAS PARA FINS DIDÁTICOS*/
SELECT NOME_DO_LIVRO,NOME_DA_EDITORA FROM LIVROS;
SELECT NOME_DO_LIVRO,ESTADO_UF_DA_EDITORA FROM LIVROS WHERE SEXO_DO_AUTOR = 'M';
SELECT NOME_DO_LIVRO,NÚMERO_DE_PÁGINAS FROM LIVROS WHERE SEXO_DO_AUTOR = 'F';
SELECT VALOR_DO_LIVRO FROM LIVROS WHERE ESTADO_UF_DA_EDITORA = 'SP';


SELECT NOME_DO_AUTOR,SEXO_DO_AUTOR,ESTADO_UF_DA_EDITORA FROM LIVROS 
WHERE SEXO_DO_AUTOR = 'M' AND (ESTADO_UF_DA_EDITORA = 'SP' OR ESTADO_UF_DA_EDITORA = 'RJ');