CREATE DATABASE BANCO_01
GO

USE BANCO_01
GO

CREATE TABLE TESTE(
	NOME VARCHAR(30)
	)
GO

Comando(s) concluído(s) com êxito.

/*INSERINDO DADOS - NO SQL SERVER~NÃO PRECISA COLOCAR 'NULL' NO ID (PRIMEIRO CAMPO), POIS O 
SISTEMA IDENTIFICA AUTOMATICAMENTE*/
INSERT INTO ALUNO VALUES('ANDRE','M','1981/12/09','ANDRE@IG.COM')
INSERT INTO ALUNO VALUES('ANA','F','1978/03/09','ANA@IG.COM')
INSERT INTO ALUNO VALUES('RUI','M','1997/07/14','RUI@IG.COM')
INSERT INTO ALUNO VALUES('JOAO','M','1975/01/27','JOAO@IG.COM')
GO