/* O servidor de maquinas gerou um arquivo de log CSV.
Vamos importá-lo e analisa-lo dentro do nosso banco */

/*Importando CSV

CRIANDO A TABELA CONFORME O ARQUIVO CSV:*/

CREATE TABLE MAQUINAS(
  MAQUINA VARCHAR(20),
  DIA INT,
  QTD NUMERIC(10,2)
);

/*PUXANDO O ARQUIVO:*/
COPY MAQUINAS
FROM 'Z:\LogMaquinas.csv' 
DELIMITER ','
CSV HEADER;


/*QUAL A MEDIA DE CADA MAQUINA */
SELECT MAQUINA, AVG(QTD) AS MEDIA_QTD
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 2 DESC;

/*ARREDONDANDO: ROUND(COLUNA,2) */
SELECT MAQUINA, ROUND(AVG(QTD),2) AS MEDIA_QTD
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 2 DESC;

------------------------------------------------------------
/* QUAL A MODA DAS QUANTIDADES */
select maquina, qtd, count(*) as moda
from maquinas
group by maquina, qtd
order by 3 desc

/* QUAL A MODA DAS QUANTIDADES DE CADA MAQUINA */
SELECT MAQUINA, QTD, COUNT(*) FROM MAQUINAS
WHERE MAQUINA = 'Maquina 01'
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC
LIMIT 1;

SELECT MAQUINA, QTD, COUNT(*) FROM MAQUINAS
WHERE MAQUINA = 'Maquina 02'
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC
LIMIT 1;

SELECT MAQUINA, QTD, COUNT(*) FROM MAQUINAS
WHERE MAQUINA = 'Maquina 03'
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC
LIMIT 1;

/* moda do dataset inteiro: HISTOGRAMA (QUANTAS VEZES ALGO OCORREU): */

SELECT  QTD, COUNT(*) AS MODA
FROM MAQUINAS
GROUP BY QTD
ORDER BY 2 DESC;

------------------------------------------------------------
/* QUAL O MAXIMO E MINIMO E AMPLITUDE DE CADA MAQUINA? */

SELECT MAQUINA,
     MAX(QTD) AS MAXIMO,
     MIN(QTD) AS MINIMO,
     MAX(QTD) - MIN(QTD) AS AMPLITUDE
     FROM MAQUINAS
     GROUP BY MAQUINA
     ORDER BY 4 DESC;

/* ACRESCENTE A MEDIA AO RELATÓRIO: */

SELECT MAQUINA,
     ROUND(AVG(QTD),2) AS MEDIA,
     MAX(QTD) AS MAXIMO,
     MIN(QTD) AS MINIMO,
     MAX(QTD) - MIN(QTD) AS AMPLITUDE
     FROM MAQUINAS
     GROUP BY MAQUINA
     ORDER BY 4 DESC;

------------------------------------------------------------
/* DESVIO PADRÃO E VARIÂNCIA */

STDDEV_POP(coluna) = desvio padrão
e 
VAR_POP(coluna) = variancia 

SELECT MAQUINA,
     ROUND(AVG(QTD),2) AS MEDIA,
     MAX(QTD) AS MAXIMO,
     MIN(QTD) AS MINIMO,
     MAX(QTD) - MIN(QTD) AS AMPLITUDE,
     ROUND(STDDEV_POP(QTD),2) AS DESV_PAD,
     ROUND(VAR_POP(QTD),2) AS VARIANCIA
     FROM MAQUINAS
     GROUP BY MAQUINA
     ORDER BY 4 DESC;

------------------------------------------------------------
/*MEDIANA: 

ESTA FUNÇÃO NÃO POSSUI UM CÓDIGO PRONTO, MAS DÁ PARA CRIÁ-LA. 
PORÉM, ESSA FÓRMULA JÁ TEM NO PROPRIO MANUAL DO POSTGRESQL, BASTA COPIAR E COLAR*/

CREATE OR REPLACE FUNCTION _final_median(NUMERIC[])
   RETURNS NUMERIC AS
$$
   SELECT AVG(val)
   FROM (
     SELECT val
     FROM unnest($1) val
     ORDER BY 1
     LIMIT  2 - MOD(array_upper($1, 1), 2)
     OFFSET CEIL(array_upper($1, 1) / 2.0) - 1
   ) sub;
$$
LANGUAGE 'sql' IMMUTABLE;

CREATE AGGREGATE median(NUMERIC) (
  SFUNC=array_append,
  STYPE=NUMERIC[],
  FINALFUNC=_final_median,
  INITCOND='{}'
);

/*APLICANDO E PROJETANDO COM O SELECT:*/
SELECT MEDIAN(QTD) AS MEDIANA
FROM MAQUINAS;

SELECT MEDIAN(QTD) AS MEDIANA
FROM MAQUINAS
WHERE MAQUINA = 'Maquina 01';
                
SELECT MEDIAN(QTD) AS MEDIANA
FROM MAQUINAS
WHERE MAQUINA = 'Maquina 02';
                     
SELECT MEDIAN(QTD) AS MEDIANA
FROM MAQUINAS
WHERE MAQUINA = 'Maquina 03';

INSERT INTO MAQUINAS VALUES('Maquina 01',11,15.9);
INSERT INTO MAQUINAS VALUES('Maquina 02',11,15.4);
INSERT INTO MAQUINAS VALUES('Maquina 03',11,15.7);
INSERT INTO MAQUINAS VALUES('Maquina 01',12,30);
INSERT INTO MAQUINAS VALUES('Maquina 02',12,24);
INSERT INTO MAQUINAS VALUES('Maquina 03',12,45);

delete from maquinas where dia = 11 or dia = 12;

------------------------------------------------------------
/*JUNTANDO TUDO:

  QUANTIDADE
  TOTAL
  MEDIA
  MAXIMO
  MINIMO
  AMPLITUDE
  VARIANCIA
  DESVIO PADRAO
  MEDIANA
  COEFICIENTE DE VARIAÇÃO.
*/

SELECT MAQUINA,
     COUNT(QTD) AS "QUANTIDADE",
     SUM(QTD) AS "TOTAL",
     ROUND(AVG(QTD),2) AS "MEDIA",
     MAX(QTD) AS "MAXIMO",
     MIN(QTD) AS "MINIMO",
     MAX(QTD) - MIN(QTD) AS "AMPLIT. TOTAL",
     ROUND(VAR_POP(QTD),2) AS "VARIANCIA",
     ROUND(STDDEV_POP(QTD),2) AS "DESV. PADRAO",
     ROUND(MEDIAN(QTD),2) AS "MEDIANA",
     ROUND((STDDEV_POP(QTD) / AVG(QTD)) * 100,2) AS "COEF. VARIACAO"
     FROM MAQUINAS
     GROUP BY MAQUINA
     ORDER BY 1;


/*ADICIONANDO A MODA:*/

/*SELECT MODE() WITHIN GROUP(ORDER BY QTD) AS "MODA" FROM MAQUINAS;*/

SELECT MAQUINA, MODE() WITHIN GROUP(ORDER BY QTD) AS "MODA" 
FROM MAQUINAS
GROUP BY MAQUINA;

/*ADICIONANDO ISSO À QUERY ANTERIOR*/
----------------------
SELECT MAQUINA,
     COUNT(QTD) AS "QUANTIDADE",
     SUM(QTD) AS "TOTAL",
     ROUND(AVG(QTD),2) AS "MEDIA",
     MAX(QTD) AS "MAXIMO",
     MIN(QTD) AS "MINIMO",
     MAX(QTD) - MIN(QTD) AS "AMPLIT. TOTAL",
     ROUND(VAR_POP(QTD),2) AS "VARIANCIA",
     ROUND(STDDEV_POP(QTD),2) AS "DESV. PADRAO",
     ROUND(MEDIAN(QTD),2) AS "MEDIANA",
     ROUND((STDDEV_POP(QTD) / AVG(QTD)) * 100,2) AS "COEF. VARIACAO",
     MODE() WITHIN GROUP(ORDER BY QTD) AS "MODA"
     FROM MAQUINAS
     GROUP BY MAQUINA
     ORDER BY 1;
----------------------

